version: "3.9"
services:
  server:
    env_file:
      - "config/.env"
    image: l1ving/heartbeat
    volumes:
      - "./config:/heartbeat/config"
    ports:
      - "${HB_PORT}:${HB_PORT}"
    build:
      context: .

  database:
    image: redislabs/rejson:latest
    volumes:
      - "redis_data:/data"
      - "./config/redis.conf:/heartbeat/config/redis.conf"
    command: "/heartbeat/config/redis.conf --loadmodule /usr/lib/redis/modules/rejson.so"
    expose:
      - 6379
    ports:
      - "6379:6379"

volumes:
  redis_data:
