version: "3.9"
services:
  server:
    image: l1ving/heartbeat
    volumes:
      - "./config:/heartbeat/config"
    ports:
      - "6060:6060"
    build:
      context: .

  database:
    image: redislabs/rejson:latest
    volumes:
      - "./config:/heartbeat/config"
    command: "/heartbeat/config/redis.conf"
    expose:
      - 6379
    ports:
      - "6379:6379"

