version: "3.9"
services:
  server:
    image: l1ving/heartbeat
    environment:
      - "ADDRESS=\"localhost:6011\""
    volumes:
      - "$HB_PATH:/heartbeat/config"
    ports:
      - "6060:6060"
      - "80:80"
    build:
      context: .
      network: "host"

  database:
    image: redislabs/rejson:latest
    ports:
      - "6379:6379"

