// Code generated by qtc from "privacypolicypage.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/privacypolicypage.qtpl:1
package templates

//line templates/privacypolicypage.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/privacypolicypage.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/privacypolicypage.qtpl:2
type PrivacyPolicyPage struct {
	ServerName string
}

//line templates/privacypolicypage.qtpl:7
func (p *PrivacyPolicyPage) StreamTitle(qw422016 *qt422016.Writer) {
//line templates/privacypolicypage.qtpl:7
	qw422016.N().S(`
    Privacy Policy - `)
//line templates/privacypolicypage.qtpl:8
	qw422016.E().S(p.ServerName)
//line templates/privacypolicypage.qtpl:8
	qw422016.N().S(`
`)
//line templates/privacypolicypage.qtpl:9
}

//line templates/privacypolicypage.qtpl:9
func (p *PrivacyPolicyPage) WriteTitle(qq422016 qtio422016.Writer) {
//line templates/privacypolicypage.qtpl:9
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/privacypolicypage.qtpl:9
	p.StreamTitle(qw422016)
//line templates/privacypolicypage.qtpl:9
	qt422016.ReleaseWriter(qw422016)
//line templates/privacypolicypage.qtpl:9
}

//line templates/privacypolicypage.qtpl:9
func (p *PrivacyPolicyPage) Title() string {
//line templates/privacypolicypage.qtpl:9
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/privacypolicypage.qtpl:9
	p.WriteTitle(qb422016)
//line templates/privacypolicypage.qtpl:9
	qs422016 := string(qb422016.B)
//line templates/privacypolicypage.qtpl:9
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/privacypolicypage.qtpl:9
	return qs422016
//line templates/privacypolicypage.qtpl:9
}

//line templates/privacypolicypage.qtpl:11
func (p *PrivacyPolicyPage) StreamHead(qw422016 *qt422016.Writer) {
//line templates/privacypolicypage.qtpl:11
	qw422016.N().S(`
`)
//line templates/privacypolicypage.qtpl:12
}

//line templates/privacypolicypage.qtpl:12
func (p *PrivacyPolicyPage) WriteHead(qq422016 qtio422016.Writer) {
//line templates/privacypolicypage.qtpl:12
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/privacypolicypage.qtpl:12
	p.StreamHead(qw422016)
//line templates/privacypolicypage.qtpl:12
	qt422016.ReleaseWriter(qw422016)
//line templates/privacypolicypage.qtpl:12
}

//line templates/privacypolicypage.qtpl:12
func (p *PrivacyPolicyPage) Head() string {
//line templates/privacypolicypage.qtpl:12
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/privacypolicypage.qtpl:12
	p.WriteHead(qb422016)
//line templates/privacypolicypage.qtpl:12
	qs422016 := string(qb422016.B)
//line templates/privacypolicypage.qtpl:12
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/privacypolicypage.qtpl:12
	return qs422016
//line templates/privacypolicypage.qtpl:12
}

//line templates/privacypolicypage.qtpl:14
func (p *PrivacyPolicyPage) StreamBody(qw422016 *qt422016.Writer) {
//line templates/privacypolicypage.qtpl:14
	qw422016.N().S(`
    <div class="spacer"></div>
    <div class="pure-g privacy">
        <div class="pure-g-u-0 pure-u-lg-1-6"></div>
        <div class="pure-u-1 pure-u-lg-4-6">
            <p class="center">
                Heartbeat Privacy Information<br><br>
                Heartbeat only keeps logs to stdout (terminal output). <br>
                IP Addresses are only logged on: <br>
            </p>
            <p>
                - Any POST requests. <br>
                - Non-GET requests on anything except the main page. <br>
                - GET requests on non-existent pages. <br>
            </p>
            <p class="center">
                <b>Your IP address will not be logged for normal requests.</b> <br>
                Logs are not shared with anybody.
            </p>
        </div>
        <div class="pure-g-u-0 pure-u-lg-1-6"></div>
    </div>
    <div class="spacer"></div>
    <div class="pure-g links">
        <div class="pure-g-u-0 pure-u-lg-1-6"></div>
        <div class="pure-u-1 pure-u-lg-4-6">
            <p class="center">
                <a href="/">Main Page</a> - <a href="/stats">Stats</a>
            </p>
        </div>
        <div class="pure-g-u-0 pure-u-lg-1-6"></div>
    </div>
`)
//line templates/privacypolicypage.qtpl:46
}

//line templates/privacypolicypage.qtpl:46
func (p *PrivacyPolicyPage) WriteBody(qq422016 qtio422016.Writer) {
//line templates/privacypolicypage.qtpl:46
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/privacypolicypage.qtpl:46
	p.StreamBody(qw422016)
//line templates/privacypolicypage.qtpl:46
	qt422016.ReleaseWriter(qw422016)
//line templates/privacypolicypage.qtpl:46
}

//line templates/privacypolicypage.qtpl:46
func (p *PrivacyPolicyPage) Body() string {
//line templates/privacypolicypage.qtpl:46
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/privacypolicypage.qtpl:46
	p.WriteBody(qb422016)
//line templates/privacypolicypage.qtpl:46
	qs422016 := string(qb422016.B)
//line templates/privacypolicypage.qtpl:46
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/privacypolicypage.qtpl:46
	return qs422016
//line templates/privacypolicypage.qtpl:46
}
