// Code generated by qtc from "statspage.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/statspage.qtpl:1
package templates

//line templates/statspage.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/statspage.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/statspage.qtpl:2
type StatsPage struct {
	TotalBeats   string
	TotalDevices string
	TotalVisits  string
	TotalUptime  string
	ServerName   string
}

//line templates/statspage.qtpl:11
func (p *StatsPage) StreamTitle(qw422016 *qt422016.Writer) {
//line templates/statspage.qtpl:11
	qw422016.N().S(`
    Stats - `)
//line templates/statspage.qtpl:12
	qw422016.E().S(p.ServerName)
//line templates/statspage.qtpl:12
	qw422016.N().S(`
`)
//line templates/statspage.qtpl:13
}

//line templates/statspage.qtpl:13
func (p *StatsPage) WriteTitle(qq422016 qtio422016.Writer) {
//line templates/statspage.qtpl:13
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/statspage.qtpl:13
	p.StreamTitle(qw422016)
//line templates/statspage.qtpl:13
	qt422016.ReleaseWriter(qw422016)
//line templates/statspage.qtpl:13
}

//line templates/statspage.qtpl:13
func (p *StatsPage) Title() string {
//line templates/statspage.qtpl:13
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/statspage.qtpl:13
	p.WriteTitle(qb422016)
//line templates/statspage.qtpl:13
	qs422016 := string(qb422016.B)
//line templates/statspage.qtpl:13
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/statspage.qtpl:13
	return qs422016
//line templates/statspage.qtpl:13
}

//line templates/statspage.qtpl:15
func (p *StatsPage) StreamHead(qw422016 *qt422016.Writer) {
//line templates/statspage.qtpl:15
	qw422016.N().S(`
`)
//line templates/statspage.qtpl:16
}

//line templates/statspage.qtpl:16
func (p *StatsPage) WriteHead(qq422016 qtio422016.Writer) {
//line templates/statspage.qtpl:16
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/statspage.qtpl:16
	p.StreamHead(qw422016)
//line templates/statspage.qtpl:16
	qt422016.ReleaseWriter(qw422016)
//line templates/statspage.qtpl:16
}

//line templates/statspage.qtpl:16
func (p *StatsPage) Head() string {
//line templates/statspage.qtpl:16
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/statspage.qtpl:16
	p.WriteHead(qb422016)
//line templates/statspage.qtpl:16
	qs422016 := string(qb422016.B)
//line templates/statspage.qtpl:16
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/statspage.qtpl:16
	return qs422016
//line templates/statspage.qtpl:16
}

//line templates/statspage.qtpl:18
func (p *StatsPage) StreamBody(qw422016 *qt422016.Writer) {
//line templates/statspage.qtpl:18
	qw422016.N().S(`
    <div class="spacer"></div>
    <div class="pure-g preamble">
        <div class="pure-g-u-0 pure-u-lg-1-6"></div>
        <div class="pure-u-1 pure-u-lg-4-6">
            <p class="center">
                Statistics for `)
//line templates/statspage.qtpl:24
	qw422016.E().S(p.ServerName)
//line templates/statspage.qtpl:24
	qw422016.N().S(`
            </p>
        </div>
        <div class="pure-g-u-0 pure-u-lg-1-6"></div>
    </div>
    <div class="pure-g times">
        <div class="pure-u-0 pure-u-lg-1-6"></div>
        <div class="pure-u-1 pure-u-lg-1-6">
            <p class="center">Total visits:<br>`)
//line templates/statspage.qtpl:32
	qw422016.E().S(p.TotalVisits)
//line templates/statspage.qtpl:32
	qw422016.N().S(`</p>
        </div>
        <div class="pure-u-1 pure-u-lg-1-6">
            <p class="center">Total devices sending beats:<br>`)
//line templates/statspage.qtpl:35
	qw422016.E().S(p.TotalDevices)
//line templates/statspage.qtpl:35
	qw422016.N().S(`</p>
        </div>
        <div class="pure-u-1 pure-u-lg-1-6">
            <p class="center">Total beats received:<br>`)
//line templates/statspage.qtpl:38
	qw422016.E().S(p.TotalBeats)
//line templates/statspage.qtpl:38
	qw422016.N().S(`</p>
        </div>
        <div class="pure-u-1 pure-u-lg-1-6">
            <p class="center">Total uptime:<br>`)
//line templates/statspage.qtpl:41
	qw422016.E().S(p.TotalUptime)
//line templates/statspage.qtpl:41
	qw422016.N().S(`</p>
        </div>
        <div class="pure-u-0 pure-u-lg-1-6"></div>
    </div>
    <div class="spacer"></div>
    <div class="pure-g links">
        <div class="pure-g-u-0 pure-u-lg-1-6"></div>
        <div class="pure-u-1 pure-u-lg-4-6">
            <p class="center">
                <a href="/">Main Page</a> - <a href="/privacy">Privacy Policy</a>
            </p>
        </div>
        <div class="pure-g-u-0 pure-u-lg-1-6"></div>
    </div>
`)
//line templates/statspage.qtpl:55
}

//line templates/statspage.qtpl:55
func (p *StatsPage) WriteBody(qq422016 qtio422016.Writer) {
//line templates/statspage.qtpl:55
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/statspage.qtpl:55
	p.StreamBody(qw422016)
//line templates/statspage.qtpl:55
	qt422016.ReleaseWriter(qw422016)
//line templates/statspage.qtpl:55
}

//line templates/statspage.qtpl:55
func (p *StatsPage) Body() string {
//line templates/statspage.qtpl:55
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/statspage.qtpl:55
	p.WriteBody(qb422016)
//line templates/statspage.qtpl:55
	qs422016 := string(qb422016.B)
//line templates/statspage.qtpl:55
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/statspage.qtpl:55
	return qs422016
//line templates/statspage.qtpl:55
}
